version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: phonebook-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin123!
      MYSQL_DATABASE: phonebook
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3